### ISSUE TITLE
[CS:GO] URL Empty error log

### ISSUE THREAD

**Issue by Ketz1337** [Vauff/AdvancedAutoRetry#1]
Hi.

The old version works, the new version doesn't. The token and url are also entered.
I'm using the latest Rest in Pawn extension.

**Error Log:**
```
L 09/13/2021 - 09:45:32: [SM] Exception reported: URL cannot be empty.
L 09/13/2021 - 09:45:32: [SM] Blaming: AdvancedAutoRetry.smx
L 09/13/2021 - 09:45:32: [SM] Call stack trace:
L 09/13/2021 - 09:45:32: [SM]   [0] HTTPRequest.HTTPRequest
L 09/13/2021 - 09:45:32: [SM]   [1] Line 244, AdvancedAutoRetry.sp::SendApiHttpRequest
L 09/13/2021 - 09:45:32: [SM]   [2] Line 98, AdvancedAutoRetry.sp::OnClientPostAdminCheck
```

**Comment by Vauff** [comment]
Are you editing the cvars in `csgo/cfg/sourcemod/AdvancedAutoRetry.cfg`? This file was added in the new version, and will likely override your values if you're setting them elsewhere.

If you're already doing that, what does `sm_cvar sm_aar_api_url` return while this error is happening?

**Comment by Ketz1337** [comment]
`sm_cvar sm_aar_api_url` and `csgo/cfg/sourcemod/AdvancedAutoRetry.cfg` returns the correct value.

**Comment by Vauff** [comment]
Can you show the exact command output and what sm_aar_api_url looks like in the .cfg? I am unable to recreate this so far.

**Comment by Ketz1337** [comment]
It already works, the problem was that I wrote the url and token into the plugin code, if I only write it to the cfg file it works, sorry for my inattention. Thanks for the help.
